version: "3.8"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dplatform
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    image: dplatform:1.0
    depends_on:
      - db
    ports:
      - "8080:8080"